### ISSUE TITLE
Can't Skip Manual Staff Role assignment

### ISSUE THREAD

**Issue by dinghow100** [Zesty-Quest/Quest-Verify-FiveM-Discord-Bot#1]
Is this a possibility
Where the system can auto give a role once they've filled out the form?

**Comment by Zesty-ZDev** [comment]
Certainly can I’ll make a new branch can you open a ticket in the community discord and I’ll message  you in the ticket once the branch is complete around tomorrow sometime and I’ll even help you integrate it if you need? 

https://discord.gg/9T7p9HjTQt
